config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'homes#top'
  
  get 'about' =>'homes#about', as: 'about'
  
  resources :users
  resources :books do
    resource :favorites
    resources :book_comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments
  validates :title, presence: true
  validates :option, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_one_attached :profile_image
         has_many :books
         has_many :favorites, dependent: :destroy
         has_many :book_comment
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comment.new(book_comment_params)
    book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to request.referer, notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render "index"
      @book = Book.new
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :option, :profile_image)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/_errors.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/books/_form.html.erb
<h2>User info</h2>
<% if user.profile_image.attached? %>
  <%= image_tag user.profile_image,size:"100x100" %>
<% else %>
  <%= image_tag 'no_image', size: "100x100" %>
<% end %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>

<div class="row">
  <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-gear"></i>
  <% end %>
</div>

  <h2>New book</h2>
  <%= form_with model: book, method: :post do |f| %>
    <h3>Title</h3>
      <%= f.text_field :title, class: "form-control" %>
    <h3>Oprion</h3>
      <%= f.text_area :option, class: "form-control" %><br>
      <%= f.submit "Create Book" %>
  <% end %>

  <select name='add'>
    <option value="未選択">'選択してください'</option>
      <?php
        for($a=1; $a<=10; $a++){
          echo"<option value='{$a}'>{$a}</option>"
        }
      ?>
  </select>

app/views/books/_thead.html.erb
<thead>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th></th>
</thead>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<table class="table">
  <tr>
    <%= form_with model: @book do |f| %>
      <h3>Title</h3>
        <%= f.text_field :title %>
      <h3>Option</h3>
        <%= f.text_area :option %>
        <%= f.submit "Update Book" %>
    <% end %>
  </tr>
</table>
<div>
  <%= link_to "show", book_path(@book) %>|
  <%= link_to "Back", :back %>
</div>

app/views/books/index.html.erb
<div class="container">
  <%= render 'errors', book: @book %>
  <div class="row">
    <div class="col-3">
      <%= render 'form', user: @user, book: @book %>
    </div>
    <div class="col-9">
      <h1>Book</h1>
        <table class="table">
          <tr>
            <%= render 'thead' %>
          </tr>
          <% @books.each do |book| %>
          <tr>
            <td>
              <% if book.user.profile_image.attached? %>
                <%= image_tag book.user.profile_image,size:"100x100" %>
              <% else %>
                <%= image_tag 'no_image', size: "100x100" %>
              <% end %>
            </td>
            <td><%= book.title %></td>
            <td><%= link_to book.option, book_path(book.id) %></td>
            <td id = "favorite_buttons_<%= book.id %>">
              <%= render "favorites/favorites", book: book %>
            </td>
          </tr>
          <% end %>
        </table>

    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render 'form', user: @user, book: @book_new %>
    </div>
    <div class="col-8">
      <table class="table">
        <tr>
          <%= render 'thead' %>
        </tr>
        <tr>
          <td>
            <% if @book.user.profile_image.attached? %>
              <%= image_tag @book.user.profile_image,size:"100x100" %>
            <% else %>
              <%= image_tag 'no_image', size: "100x100" %>
            <% end %>
          </td>
          <td><%= @book.title %></td>
          <td><%= link_to @book.option, book_path(@book) %></td>
          <% if @user == current_user %>
          <td><%= link_to "Edit", edit_book_path(@book) %></td>
          <td><%= link_to "Destroy", book_path(@book), method: :delete %></td>
          <% end %>
        </tr>
      </table>
      <% @book.book_comments.each do |book_comment| %>
        <p image_tag book_comments.user.profile_image(100, 100)></p>
        <%= book_comment.user.name %>
        <%= book_comment.comment %>
      <% end %>

      <%= form_for [@book, @book_comment] do |f| %>
        <%= f.text_area :comment, rows: 5, placeholder: 'コメントをここに' %>
        <%= f.submit '送信' %>
      <% end %>
    </div>
  </div>
</div>

app/views/favorites/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♡<%=book.favorites.count %>いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♥<%= book.favorites.count %>いいね
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/homes/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
         <p> CopyRight Infratop.inc </p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/_header.html.erb
<header style="background-color:#212529;">
  <div class="container">
    <div class="row">
      <div class=" col-4 mr-auto m-3">
        <%= link_to root_path do %>
         <span class="mr-auto">Bookers</span>
        <% end %>
      </div>
      <div class=" col-4 ml-auto m-3">
        <% if user_signed_in? %>
          <%= link_to user_path(current_user) do %>
            <i class="fa-solid fa-house">Home</i>
          <% end %>

          <%= link_to users_path do %>
            <i class="fa-solid fa-link">User</i>
          <% end %>

          <%= link_to books_path do %>
            <i class="fa-solid fa-user-plus">Books</i>
          <% end %>

          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa-solid fa-arrow-right-to-bracket">Log out</i>
          <% end %>
      <% else %>
        <%= link_to root_path do %>
          <i class="fa-solid fa-house">Home</i>
        <% end %>

        <%= link_to about_path do %>
          <i class="fa-solid fa-link">About</i>
        <% end %>

        <%= link_to new_user_registration_path do %>
          <i class="fa-solid fa-user-plus">Sign up</i>
        <% end %>

        <%= link_to new_user_session_path do %>
          <i class="fa-solid fa-arrow-right-to-bracket">Log in</i>
        
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
</header>

app/views/homes/top.html.erb
<div class="container"%>
  <div class="row">
    <div class="col-6 m-auto">
  
      <h1>welcome to 
          <i class="fa-solid fa-book"></i>bookers!!</h1>
      <p>in <i class="fa-solid fa-book"></i>bookers<br>
         you can share and exchange your opinions , inpressions , and emotions<br>
         about various books!
      </p>
      <%= link_to "log in", new_user_session_path, class:"btn btn-info btn-sm btn-block" %><br>
      <%= link_to "sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5c4a1fefd6.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% else %>
      <%= flash[:alert] %>
    <% end %>

    <%= render "homes/header" %>
    <%= yield %>
    <%= render "homes/footer" %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_with model: @user do |f| %>
  <h3>Name</h3>
    <%= f.text_field:name %>
  <h3>Image</h3>
    <%= f.file_field :profile_image, accept: "image/*" %>
  <h3>Introduction</h3>
    <%= f.text_area :introduction %>
    <%=f.submit "Update User" %>
  <% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render 'books/form', user: @user, book: @book %>
    </div>
    <div class="col-8">
      <h1>User</h1>
      <table class="table">
        <thead>
          <th>Image</th>
          <th>Name</th>
          <th></th>
        </thead>
        <% @users.each do |user| %>
            <tr>
              <td>
                <% if user.profile_image.attached? %>
                  <%= image_tag user.profile_image,size:"100x100" %>
                <% else %>
                  <%= image_tag 'no_image', size: "100x100" %>
                <% end %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user) %>
              </td>
            </tr>
          <% end %>
        </table>
    </div>
  </div> 
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h2>User info</h2>
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image,size:"100x100" %>
      <% else %>
        <%= image_tag 'no_image', size: "100x100" %>
      <% end %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>

      <div class="row">
        <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fa-solid fa-user-gear"></i>
        <% end %>
      </div>

        <h2>New book</h2>
        <%= form_with model: Book, method: :post do |f| %>
          <h3>Title</h3>
            <%= f.text_field :title, class: "form-control" %>
          <h3>Oprion</h3>
            <%= f.text_area :option, class: "form-control" %><br>
            <%= f.submit "Create Book" %>
        <% end %>
    </div>

    <div class="col-9">
      <h1 class="m-5">Book detail</h1>

        <table class="table mx-5">
          <tr>
            <thead>
              <th></th>
              <th>Title</th>
              <th>Option</th>
              <th></th>
              <th></th>
            </thead>
          </tr>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <% if book.user.profile_image.attached? %>
                  <%= image_tag book.user.profile_image,size:"100x100" %>
                <% else %>
                  <%= image_tag 'no_image', size: "100x100" %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book) %>
            </td>
            <td>
              <%= book.option %>
            </td>
            <td>
              <%= link_to "Edit", edit_book_path(book.user) %>
            </td>
            <td>
              <%= link_to "Destroy", book_path(book.id), method: :delete %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>